# Generated by Django 4.2.4 on 2023-09-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('wheelchair', 'Wheelchair'), ('walker', 'Walker'), ('crutches', 'Crutches')], default='default', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
